language: java
sudo: true
script:
  - mpn install
  - bash scripts/surge_deploy.sh
deploy:
  - provider: script
    skip_cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      repo: nimeshkasun/Intake34FOC
      branch: master